//try and catch

const  a = 5;
const  b = 10 ;
 try{
  console.log(a+b);
  console.log(a+b+c);
  console.log("hello")
 }catch(err){
  console.log(err)
 }

 console.log(a+b);
 console.log(a+10)
 console.log(10+10)
 